import { Montserrat, Permanent_Marker } from "next/font/google";
// 1. import `NextUIProvider` component
import {NextUIProvider} from "@nextui-org/system";
import "./globals.css";

const inter = Montserrat({ subsets: ["latin"], variable: '--font-inter' });
const permanent_marker = Permanent_Marker({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: '--font-permanent-marker',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className={`${inter.variable} ${permanent_marker.variable} font-sans`}>
          <NextUIProvider>
            {children}
          </NextUIProvider>
        </body>
      </html>
  );
}
